E0 = [{
        "root":"gr",
    	"tense": 'present',
    	"passive": False,
    	"parent_place_string": '',
    	"person": ['me', 'plural-you'],
    	"professional": None,
    	"child_place_string": '',
    	"parent_place": [],
    	"verb_class": 'indicative',
    	"metaphore": False,
    	"child_place": [],
    	"class": 'verb',
    }, # tagökoxixin(ri)
    {
        "root":"kx",
    	"number": 'plural',
    	"parent_place_string": '',
    	"child_place_string": '',
    	"professional": True,
    	"metaphore": True,
    	"passive": False,
    	"case_class": None,
    	"parent_place": [],
    	"noun_class": 'actor',
    	"case": None,
    	"child_place": [],
    	"class": 'noun',
    }, # (ri)poPulokema
    {
        "root":"pP",
    	"number": 'singular',
    	"parent_place_string": '',
    	"child_place_string": '',
    	"professional": None,
    	"metaphore": False,
    	"passive": False,
    	"case_class": 'causal',
    	"parent_place": [],
    	"noun_class": 'action',
    	"case": 'opposite',
    	"child_place": [],
    	"class": 'noun',
    }, # rilomamaxedewOti
    {
        "root":"lmd",
    	"number": 'singular',
    	"parent_place_string": '',
    	"child_place_string": '',
    	"professional": True,
    	"metaphore": False,
    	"passive": True,
    	"case_class": 'directional',
    	"parent_place": [],
    	"noun_class": 'action',
    	"case": 'near',
    	"child_place": [],
    	"class": 'noun',
    }, # JuvomusaqemalesO
    {
        "root":"vmq",
    	"number": 'singular',
    	"parent_place_string": '',
    	"child_place_string": '',
    	"professional": None,
    	"metaphore": False,
    	"passive": False,
    	"case_class": 'causal',
    	"parent_place": [],
    	"noun_class": 'action',
    	"case": 'before',
        "child_place": [],
        "class": 'noun',
    }, # lelomuxedan
    {
        "root":"lmd",
    	"number": 'plural',
    	"parent_place_string": '',
    	"child_place_string": '',
    	"professional": None,
    	"metaphore": False,
    	"passive": True,
    	"case_class": None,
    	"parent_place": [],
    	"noun_class": 'actor',
    	"case": None,
    	"child_place": [],
    	"class": 'noun',
    }, # sOlomidin
    {
        "root":"lmd",
    	"number": 'plural',
    	"parent_place_string": '',
    	"child_place_string": '',
    	"professional": True,
    	"metaphore": False,
    	"passive": False,
    	"case_class": None,
    	"parent_place": [],
    	"noun_class": 'actor',
    	"case": None,
    	"child_place": [],
    	"class": 'noun',
    }, { #"regularly in the time of the shone upon", dayly
        "root":"vXn",
    	"number": 'singular',
    	"parent_place_string": '',
    	"child_place_string": '',
    	"professional": False,
    	"metaphore": True,
    	"passive": True,
    	"case_class": 'temporal',
    	"parent_place": [],
    	"noun_class": 'actor',
    	"case": 'above',
    	"child_place": [],
    	"class": 'adjective',
    }, {
        "root":"KðJ",
    	"tense": 'present',
    	"passive": True,
    	"parent_place_string": '',
    	"person": ['me', 'plural-you'],
    	"professional": None,
    	"child_place_string": '',
    	"parent_place": [],
    	"verb_class": 'indicative',
    	"metaphore": False,
    	"child_place": [],
    	"class": 'verb',
}]
#                 /----------------------------\
#  v   !  v     /-|---      v       v     v  --|-v   .   v  ----\ v     v   /----\ v     v     v   v       v   .   v   .  v   .    v
# gáresùnkáj(taríJúwa) tagökóxixìn-póPulokÈma Jùlómamàxedéwoti rívómusaqÈmalèso lèlómuxedán solómidìn wagövéXekìxenírufo KáPesùnxeJáj.
# gáresunkáj(taríJuwa) tagökóxixín-póPulokéma Julómamáxedéwoti rívómusaqémaléso lélómuxedán solómidín wagövéXekéxenírufo KáPesúnxeJáj.
# you and I (go) as fighters against fire (go) into schools to save            students and teachers dayly          and we get killed.


E1 = [{
        "root":"KðJ",
    	"parent_place": [],
    	"passive": True,
    	"verb_class": 'imperative',
    	"professional": None,
    	"child_place": [],
    	"child_place_string": '',
    	"tense": 'future',
    	"metaphore": False,
    	"parent_place_string": '',
    	"class": 'verb',
	    "person": ['me'],
    }, {
        "root":"KðJ",
    	"parent_place": [],
    	"passive": True,
    	"verb_class": 'imperative',
    	"professional": None,
    	"child_place": [],
    	"child_place_string": '',
    	"tense": 'present',
    	"metaphore": False,
    	"parent_place_string": '',
    	"class": 'verb',
    	"person": ['me'],
    }, {
        "root":"KðJ",
    	"parent_place": [],
    	"passive": True,
    	"verb_class": 'imperative',
    	"professional": None,
    	"child_place": [],
    	"child_place_string": '',
    	"tense": 'past',
    	"metaphore": False,
    	"parent_place_string": '',
    	"class": 'verb',
    	"person": ['me'],
}]
