VOCAB = {
    "gr":{
        "garju":"to go",
        "garjukofE":"to stumble",
        "gögarjuxekofE":"to be made stumble metaphorically (in a conversation)",
        "gögarExekiten":"they are being thrown out by security",
        "gögarosuxekitajn":"you and we must be assaulted/killed by professionals",
    },
    "kl":{
        "kalju":"to work",
        "koluxi":"worker",
        "koloxê":"untrained worker, unqualified",
        "kolami":"work, quality",
        "kolamê":"easy work, hard labour",
        "koluti":"material",
        "kolutê":"resource",
        "kolokuma":"workplace",
        "kolosakuma":"in front of the workplace",
        "kolotajkuma":"at the workplace",
        "kolekima":"worktime",
        "koletajkima":"at the beginning of worktime",
        "kolepikima":"during worktime",
        "kolekekima":"during the working week/month/year/life",
        "kolusakema":"for the work",
        "kolurokema":"caused by the work",
        "kolukekema":"the larger reasoning about work, work philosophy, setting work in a larger context",
        "kolulukema":"the details of work, work contract, specifying work",
        "kolufokema":"loosely related to work, similar to work",
        "kolutajkemati":"the same as quality work",
        "kolupikemafo":"equivalent to lesser work",
        "kolupikema":"equivalent to work",
    },
    "lmd":{
        "lamdju":"to teach",
        "lamexdju":"to learn",
        "lomada":"teaching",
        "lomaxda":"learning",
        "lomadi":"school",
        "lomaxdi":"school, from a students perspective",
        "lomadê":"teaching badly",
        "lomaxdê":"trying to learn, but fail",
        "lomerodimati":"after school",
        "lomesadimati":"before school",
        "lomepidimati":"during school",
        "lomemadimati":"beginning time of school"
    },
    "m¶k":{
        "ma¶kju":"to rise",
        "göma¶xekju":"to be raised",
        "gömo¶amaxekerutin":"to the kindergardeners",
    }
}
roots = {
    "help":"Jlt",
    "go":"gr",
    "work":"kl",
    "fight":"kx",
    "rise":"m¶k",
    "teach":"lmd",
    "save":"vmq",
    "decorate":"Ktr",
    "inform":"Qvz",
    "burn":"p¶",
    "shine":"vXn",
    "kill":"KðJ",
}
