VOCAB = {
    "gr":{
        "garju":"to go",
        "garjukofe":"to stumble",
        "gygarjuxekofe":"to be made stumble metaphorically (in a conversation)",
        "garexekitene":"they are being thrown out by security",
        "gygarosuxekitajne":"you and we must be assassinated/killed by professionals",
    },
    "kl":{
        "kalju":"to work",
        "koluxi":"worker",
        "koloxe":"untrained worker, unqualified",
        "kolami":"work, quality",
        "kolame":"easy work",
        "koluti":"material",
        "kolute":"resource",
        "kolokuma":"workplace",
        "kolosakuma":"in front of the workplace",
        "kolotajkuma":"at the workplace",
        "kolekima":"worktime",
        "koletajkima":"at the beginning of worktime",
        "kolepikima":"during worktime",
        "kolekekima":"during the working week/month/year/life",
        "kolusakema":"for the work",
        "kolurokema":"caused by the work",
        "kolukekema":"the larger reasoning about work, work philosophy, setting work in a larger context",
        "kolulukema":"the details of work, work contract, specifying work",
        "kolufokema":"loosely related to work, similar to work",
        "kolutajkemati":"the same as quality work",
        "kolupikemafo":"equivalent to lesser work",
        "kolupikema":"equivalent to work",
    },
    "lmd":{
        "lamjud":"to teach",
        "lamexejud":"to learn",
        "lomada":"teaching",
        "lomaxeda":"learning",
        "lomadi":"school",
        "lomaxedi":"school, from a students perspective",
        "lomade":"teaching badly",
        "lomaxede":"trying to learn, but fail",
        "lomerodimati":"after school",
        "lomesadimati":"before school",
        "lomepidimati":"during school",
        "lomemadimati":"beginning time of school"
    },
    "mPk":{
        "maPjuk":"to rise",
        "gymaPjuxek":"to be raised",
        "gymoPamakerutine":"to the kindergardeners",
    }
}
roots = {
    "help":"Jlt",
    "go":"gr",
    "work":"kl",
    "fight":"kx",
    "rise":"mPk",
    "teach":"lmd",
    "save":"vmq",
    "decorate":"Ktr",
    "inform":"qvz",
    "think":"DP",
    "burn":"pP",
    "shine":"vXn",
    "kill":"KDJ",
    "exist":"JX",
    "limit":"kwX",
    "separate":"dwr",
    "unite":"qJr",
    "speak_language":"sfm",
    "speak_words":"zw",
    "converse":"lqr",
    "place":"pz"
}
